#  Copyright 2018 U.C. Berkeley RISE Lab
# 
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

apiVersion: v1
kind: Pod
metadata:
  name: function-pod-NUM_DUMMY
  labels: 
    role: function
spec:
  volumes:
  - name: ipc
    hostPath:
      path: /tmp
  hostNetwork: true
  hostIPC: true
  containers:
  - name: function-container
    image: vsreekanti/fluent-func
    env: 
    - name: ROUTE_ADDR
      value: ROUTE_ADDR_DUMMY
    - name: MGMT_IP
      value: MGMT_IP_DUMMY
    - name: REPO_ORG
      value: vsreekanti
    - name: REPO_BRANCH
      value: func-scheduling
    - name: SCHED_IPS
      value: ''
    volumeMounts:
    - mountPath: /requests
      name: ipc
  - name: cache-container
    image: vsreekanti/fluent-cache
    env:
    - name: ROUTE_ADDR
      value: ROUTE_ADDR_DUMMY
    - name: MGMT_IP
      value: MGMT_IP_DUMMY
    - name: REPO_ORG
      value: vsreekanti
    - name: REPO_BRANCH
      value: func-scheduling
    volumeMounts:
    - mountPath: /requests
      name: ipc
  nodeSelector:
    role: function
    podid: function-NUM_DUMMY
